name: publish

on:
  push:
    branches: [ main ]

env:
  APP_NAME: Qontro.Toolkit
  APP_PACKAGE_PATH: './src/Qontro.Toolkit.Ui'
  DOTNET_VERSION: '8.0.404' 

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: |
        cd ${{ env.APP_PACKAGE_PATH }}
        dotnet restore
      
    - name: Build
      run: |
        cd ${{ env.APP_PACKAGE_PATH }}
        dotnet build --configuration Release --no-restore

    - name: Publish win-x64
      run: |
        cd ${{ env.APP_PACKAGE_PATH }}
        dotnet publish -r win-x64 -o ./publish/win_x64 -c Release -f net8.0 --self-contained
    
    - uses: bbonkr/get-version-action@v1
      id: get_version
      with:
        project: ${{ env.APP_PACKAGE_PATH }}/Qontro.Toolkit.Ui.csproj
        show_log_message: true

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: v${{ steps.get_version.outputs.version }}
        tag_name: v${{ steps.get_version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: upload win-x64 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.APP_PACKAGE_PATH }}/publish/win_x64
        asset_name: Qontro.Toolkit.win_x64.tar.gz
        asset_content_type: application/gzip
